#coding: utf-8
class DTO():

    def __init__(self):
        nom_du_joueur = None
        mot_de_passe = None
        couleur_tank_rouge = 0
        couleur_tank_vert = 0
        couleur_tank_bleu = 0
        couleurs_tank = [couleur_tank_rouge,couleur_tank_vert,couleur_tank_bleu]
        phrase_personnelle = None
        distance = 0
        gagnant = 0
        coolpoints_vie = 0 
        coolpoints_force = 0
        coolpoints_agilite = 0
        coolpoints_dexterite = 0



    