DROP TABLE emp;
DROP TABLE dep;

CREATE TABLE emp(
    ID NUMBER GENERATED by default on null as IDENTITY PRIMARY KEY,
    nom VARCHAR(32),
    dep NUMBER
);

CREATE TABLE dep(
    ID NUMBER GENERATED by default on null as IDENTITY PRIMARY KEY,
    nom VARCHAR(32),
    sup NUMBER
);

ALTER TABLE emp ADD CONSTRAINT emp_dep FOREIGN KEY (dep)REFERENCES dep (id) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE dep ADD CONSTRAINT dep_sup FOREIGN KEY (sup)REFERENCES emp (id) DEFERRABLE INITIALLY DEFERRED;

DECLARE
    idemp NUMBER;
    iddep NUMBER;
BEGIN
    INSERT INTO emp (nom) VALUES ('William') returning ID into idemp;
    INSERT INTO dep (nom) VALUES ('Informatique') returning ID into iddep;
    UPDATE emp SET dep = iddep WHERE id = idemp;
    UPDATE dep SET sup = idemp WHERE id = iddep;
    commit;
END;
/

SELECT * FROM emp;
SELECT * FROM dep;


